/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Acer
 */
public class signup extends javax.swing.JFrame {

    /**
     * Creates new form signup
     */
    public signup() {
        initComponents();
    

//     Loginred.addActionListener(new java.awt.event.ActionListener() {
//        public void actionPerformed(java.awt.event.ActionEvent evt) {
//            login loginPage = new login();
//            loginPage.setVisible(true);
//            signup.this.dispose();
//        }
//    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        FullName = new javax.swing.JLabel();
        CompanyName = new javax.swing.JLabel();
        Emaill = new javax.swing.JLabel();
        Role = new javax.swing.JLabel();
        Passwordd = new javax.swing.JLabel();
        FullNameText = new javax.swing.JTextField();
        CompanyNameText = new javax.swing.JTextField();
        EmaillText = new javax.swing.JTextField();
        RoleText = new javax.swing.JTextField();
        PasswordFieldd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        SignupButton = new javax.swing.JButton();
        Loginred = new javax.swing.JButton();
        Passworrd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("REGISTER");

        jLabel2.setText("MANAGE ALL OF OUR INVENTORY EFFICIENTLY");

        FullName.setText("Full Name");

        CompanyName.setText("Company's Name");

        Emaill.setText("Email");

        Role.setText("Role");

        Passwordd.setText("Already have a account");

        FullNameText.setText("Enter your Full Name");
        FullNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                FullNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                FullNameTextFocusLost(evt);
            }
        });
        FullNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FullNameTextActionPerformed(evt);
            }
        });

        CompanyNameText.setText("Enter your Company Name");
        CompanyNameText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                CompanyNameTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                CompanyNameTextFocusLost(evt);
            }
        });

        EmaillText.setText("Enter your email");
        EmaillText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                EmaillTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                EmaillTextFocusLost(evt);
            }
        });

        RoleText.setText("Enter your role");
        RoleText.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RoleTextFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                RoleTextFocusLost(evt);
            }
        });

        PasswordFieldd.setText("jPasswordField1");
        PasswordFieldd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFielddActionPerformed(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Screenshot 2025-06-22 233834.png"))); // NOI18N

        SignupButton.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        SignupButton.setText("Signup");
        SignupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignupButtonActionPerformed(evt);
            }
        });

        Loginred.setForeground(new java.awt.Color(255, 51, 51));
        Loginred.setText("Login");
        Loginred.setBorder(null);
        Loginred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginredActionPerformed(evt);
            }
        });

        Passworrd.setText("Password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(471, 471, 471)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(408, 408, 408)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(Emaill, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmaillText, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RoleText, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addComponent(SignupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(Passwordd, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Loginred))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(546, 546, 546)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordFieldd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Passworrd, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(FullName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(FullNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(CompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(CompanyNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(Emaill, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(EmaillText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(Role, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(RoleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(2, 2, 2)
                .addComponent(Passworrd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PasswordFieldd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(SignupButton)
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Passwordd, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Loginred))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FullNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FullNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FullNameTextActionPerformed

    private void PasswordFielddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFielddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFielddActionPerformed

    private void SignupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignupButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SignupButtonActionPerformed

    private void FullNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameTextFocusGained
        // TODO add your handling code here:
        if(FullNameText.getText().equals("Enter your Full Name")){
            FullNameText.setText("");
        }
    }//GEN-LAST:event_FullNameTextFocusGained

    private void FullNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_FullNameTextFocusLost
        // TODO add your handling code here:
        if(FullNameText.getText().isEmpty()){
        FullNameText.setText("Enter your Full Name");
        }
    }//GEN-LAST:event_FullNameTextFocusLost

    private void CompanyNameTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CompanyNameTextFocusGained
        // TODO add your handling code here:
        if(CompanyNameText.getText().equals("Enter your Company Name")){
            CompanyNameText.setText("");
        }
    }//GEN-LAST:event_CompanyNameTextFocusGained

    private void CompanyNameTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_CompanyNameTextFocusLost
        // TODO add your handling code here:
        if(CompanyNameText.getText().isEmpty()){
            CompanyNameText.setText("Enter your Company Name");
            
        }
    }//GEN-LAST:event_CompanyNameTextFocusLost

    private void EmaillTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmaillTextFocusGained
        // TODO add your handling code here:
        if(EmaillText.getText().equals("Enter your email")){
            EmaillText.setText("");
        }
    }//GEN-LAST:event_EmaillTextFocusGained

    private void EmaillTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_EmaillTextFocusLost
        // TODO add your handling code here:
        if(EmaillText.getText().isEmpty()){
            EmaillText.setText("Enter your email");
        }
    }//GEN-LAST:event_EmaillTextFocusLost

    private void RoleTextFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RoleTextFocusGained
        // TODO add your handling code here:
        if(RoleText.getText().equals("Enter your role")){
            RoleText.setText("");
        }
    }//GEN-LAST:event_RoleTextFocusGained

    private void RoleTextFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RoleTextFocusLost
        // TODO add your handling code here:
        if(RoleText.getText().isEmpty()){
            RoleText.setText("Enter your role");
        }
    }//GEN-LAST:event_RoleTextFocusLost

    private void LoginredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginredActionPerformed
        // TODO add your handling code here:
        login loginpage=new login();
        loginpage.setVisible(true);
        signup.this.dispose();
    }//GEN-LAST:event_LoginredActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CompanyName;
    private javax.swing.JTextField CompanyNameText;
    private javax.swing.JLabel Emaill;
    private javax.swing.JTextField EmaillText;
    private javax.swing.JLabel FullName;
    private javax.swing.JTextField FullNameText;
    private javax.swing.JButton Loginred;
    private javax.swing.JPasswordField PasswordFieldd;
    private javax.swing.JLabel Passwordd;
    private javax.swing.JLabel Passworrd;
    private javax.swing.JLabel Role;
    private javax.swing.JTextField RoleText;
    private javax.swing.JButton SignupButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
  public void addAddUserListener(java.awt.event.ActionListener listener) {
    SignupButton.addActionListener(listener);
}
  public void addLoginListener(java.awt.event.ActionListener listener) {
    Loginred.addActionListener(listener);
}

public javax.swing.JTextField getFullNameText() {
    return FullNameText;
}

public javax.swing.JTextField getCompanyNameText() {
    return CompanyNameText;
}

public javax.swing.JTextField getEmailText() {
    return EmaillText;
}

public javax.swing.JTextField getRoleText() {
    return RoleText;
}

public javax.swing.JPasswordField getPasswordField() {
    return PasswordFieldd;
}
}
